services:
  backend:
    environment:
      API_DEVICE: cuda:0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["${GPU_DEVICE_ID:-0}"]
              capabilities: [gpu]
